headers = ['Pt_Age:latest',
 'Caregiver_Age:latest',
 'MEMORY_CDR_No_Impairment:latest',
 'MEMORY_CDR_Questionable_Impairment:latest',
 'MEMORY_CDR_Mild_Impairment:latest',
 'MEMORY_CDR_Moderate_Impairment:latest',
 'MEMORY_CDR_Severe_Impairment:latest',
 'MEMORY_CDR_Unknown:latest',
 'ORIENT_CDR_No_Impairment:latest',
 'ORIENT_CDR_Questionable_Impairment:latest',
 'ORIENT_CDR_Mild_Impairment:latest',
 'ORIENT_CDR_Moderate_Impairment:latest',
 'ORIENT_CDR_Severe_Impairment:latest',
 'ORIENT_CDR_Unknown:latest',
 'JUDGMENT_CDR_No_Impairment:latest',
 'JUDGMENT_CDR_Questionable_Impairment:latest',
 'JUDGMENT_CDR_Mild_Impairment:latest',
 'JUDGMENT_CDR_Moderate_Impairment:latest',
 'JUDGMENT_CDR_Severe_Impairment:latest',
 'JUDGMENT_CDR_Unknown:latest',
 'COMMUN_CDR_No_Impairment:latest',
 'COMMUN_CDR_Questionable_Impairment:latest',
 'COMMUN_CDR_Mild_Impairment:latest',
 'COMMUN_CDR_Moderate_Impairment:latest',
 'COMMUN_CDR_Severe_Impairment:latest',
 'COMMUN_CDR_Unknown:latest',
 'HOMEHOBB_CDR_No_Impairment:latest',
 'HOMEHOBB_CDR_Questionable_Impairment:latest',
 'HOMEHOBB_CDR_Mild_Impairment:latest',
 'HOMEHOBB_CDR_Moderate_Impairment:latest',
 'HOMEHOBB_CDR_Severe_Impairment:latest',
 'HOMEHOBB_CDR_Unknown:latest',
 'PERSCARE_CDR_No_Impairment:latest',
 'PERSCARE_CDR_Questionable_Impairment:latest',
 'PERSCARE_CDR_Mild_Impairment:latest',
 'PERSCARE_CDR_Moderate_Impairment:latest',
 'PERSCARE_CDR_Severe_Impairment:latest',
 'PERSCARE_CDR_Unknown:latest',
 'COMPORT_CDR_No_Impairment:latest',
 'COMPORT_CDR_Questionable_Impairment:latest',
 'COMPORT_CDR_Mild_Impairment:latest',
 'COMPORT_CDR_Moderate_Impairment:latest',
 'COMPORT_CDR_Severe_Impairment:latest',
 'COMPORT_CDR_Unknown:latest',
 'CDRLANG_CDR_No_Impairment:latest',
 'CDRLANG_CDR_Questionable_Impairment:latest',
 'CDRLANG_CDR_Mild_Impairment:latest',
 'CDRLANG_CDR_Moderate_Impairment:latest',
 'CDRLANG_CDR_Severe_Impairment:latest',
 'CDRLANG_CDR_Unknown:latest',
 'DEL_NPIQ_No_Impairment:latest',
 'DEL_NPIQ_With_Impairment:latest',
 'DEL_NPIQ_Unknown:latest',
 'DELSEV_NPIQ_Mild:latest',
 'DELSEV_NPIQ_Moderate:latest',
 'DELSEV_NPIQ_Severe:latest',
 'DELSEV_NPIQ_Unknown:latest',
 'HALL_NPIQ_No_Impairment:latest',
 'HALL_NPIQ_With_Impairment:latest',
 'HALL_NPIQ_Unknown:latest',
 'HALLSEV_NPIQ_Mild:latest',
 'HALLSEV_NPIQ_Moderate:latest',
 'HALLSEV_NPIQ_Severe:latest',
 'HALLSEV_NPIQ_Unknown:latest',
 'AGIT_NPIQ_No_Impairment:latest',
 'AGIT_NPIQ_With_Impairment:latest',
 'AGIT_NPIQ_Unknown:latest',
 'AGITSEV_NPIQ_Mild:latest',
 'AGITSEV_NPIQ_Moderate:latest',
 'AGITSEV_NPIQ_Severe:latest',
 'AGITSEV_NPIQ_Unknown:latest',
 'DEPD_NPIQ_No_Impairment:latest',
 'DEPD_NPIQ_With_Impairment:latest',
 'DEPD_NPIQ_Unknown:latest',
 'DEPDSEV_NPIQ_Mild:latest',
 'DEPDSEV_NPIQ_Moderate:latest',
 'DEPDSEV_NPIQ_Severe:latest',
 'DEPDSEV_NPIQ_Unknown:latest',
 'ANX_NPIQ_No_Impairment:latest',
 'ANX_NPIQ_With_Impairment:latest',
 'ANX_NPIQ_Unknown:latest',
 'ANXSEV_NPIQ_Mild:latest',
 'ANXSEV_NPIQ_Moderate:latest',
 'ANXSEV_NPIQ_Severe:latest',
 'ANXSEV_NPIQ_Unknown:latest',
 'ELAT_NPIQ_No_Impairment:latest',
 'ELAT_NPIQ_With_Impairment:latest',
 'ELAT_NPIQ_Unknown:latest',
 'ELATSEV_NPIQ_Mild:latest',
 'ELATSEV_NPIQ_Moderate:latest',
 'ELATSEV_NPIQ_Severe:latest',
 'ELATSEV_NPIQ_Unknown:latest',
 'APA_NPIQ_No_Impairment:latest',
 'APA_NPIQ_With_Impairment:latest',
 'APA_NPIQ_Unknown:latest',
 'APASEV_NPIQ_Mild:latest',
 'APASEV_NPIQ_Moderate:latest',
 'APASEV_NPIQ_Severe:latest',
 'APASEV_NPIQ_Unknown:latest',
 'DISN_NPIQ_No_Impairment:latest',
 'DISN_NPIQ_With_Impairment:latest',
 'DISN_NPIQ_Unknown:latest',
 'DISNSEV_NPIQ_Mild:latest',
 'DISNSEV_NPIQ_Moderate:latest',
 'DISNSEV_NPIQ_Severe:latest',
 'DISNSEV_NPIQ_Unknown:latest',
 'IRR_NPIQ_No_Impairment:latest',
 'IRR_NPIQ_With_Impairment:latest',
 'IRR_NPIQ_Unknown:latest',
 'IRRSEV_NPIQ_Mild:latest',
 'IRRSEV_NPIQ_Moderate:latest',
 'IRRSEV_NPIQ_Severe:latest',
 'IRRSEV_NPIQ_Unknown:latest',
 'MOT_NPIQ_No_Impairment:latest',
 'MOT_NPIQ_With_Impairment:latest',
 'MOT_NPIQ_Unknown:latest',
 'MOTSEV_NPIQ_Mild:latest',
 'MOTSEV_NPIQ_Moderate:latest',
 'MOTSEV_NPIQ_Severe:latest',
 'MOTSEV_NPIQ_Unknown:latest',
 'NITE_NPIQ_No_Impairment:latest',
 'NITE_NPIQ_With_Impairment:latest',
 'NITE_NPIQ_Unknown:latest',
 'NITESEV_NPIQ_Mild:latest',
 'NITESEV_NPIQ_Moderate:latest',
 'NITESEV_NPIQ_Severe:latest',
 'NITESEV_NPIQ_Unknown:latest',
 'APP_NPIQ_No_Impairment:latest',
 'APP_NPIQ_With_Impairment:latest',
 'APP_NPIQ_Unknown:latest',
 'APPSEV_NPIQ_Mild:latest',
 'APPSEV_NPIQ_Moderate:latest',
 'APPSEV_NPIQ_Severe:latest',
 'APPSEV_NPIQ_Unknown:latest',
 'MEMORY_CDR_Neg_Change:6mons',
 'MEMORY_CDR_No_Change:6mons',
 'MEMORY_CDR_Positive_Change:6mons',
 'MEMORY_CDR_Unknown_Change:6mons',
 'ORIENT_CDR_Neg_Change:6mons',
 'ORIENT_CDR_No_Change:6mons',
 'ORIENT_CDR_Positive_Change:6mons',
 'ORIENT_CDR_Unknown_Change:6mons',
 'JUDGMENT_CDR_Neg_Change:6mons',
 'JUDGMENT_CDR_No_Change:6mons',
 'JUDGMENT_CDR_Positive_Change:6mons',
 'JUDGMENT_CDR_Unknown_Change:6mons',
 'COMMUN_CDR_Neg_Change:6mons',
 'COMMUN_CDR_No_Change:6mons',
 'COMMUN_CDR_Positive_Change:6mons',
 'COMMUN_CDR_Unknown_Change:6mons',
 'HOMEHOBB_CDR_Neg_Change:6mons',
 'HOMEHOBB_CDR_No_Change:6mons',
 'HOMEHOBB_CDR_Positive_Change:6mons',
 'HOMEHOBB_CDR_Unknown_Change:6mons',
 'PERSCARE_CDR_Neg_Change:6mons',
 'PERSCARE_CDR_No_Change:6mons',
 'PERSCARE_CDR_Positive_Change:6mons',
 'PERSCARE_CDR_Unknown_Change:6mons',
 'COMPORT_CDR_Neg_Change:6mons',
 'COMPORT_CDR_No_Change:6mons',
 'COMPORT_CDR_Positive_Change:6mons',
 'COMPORT_CDR_Unknown_Change:6mons',
 'CDRLANG_CDR_Neg_Change:6mons',
 'CDRLANG_CDR_No_Change:6mons',
 'CDRLANG_CDR_Positive_Change:6mons',
 'CDRLANG_CDR_Unknown_Change:6mons',
 'DEL_NPIQ_Neg_Change:6mons',
 'DEL_NPIQ_No_Change:6mons',
 'DEL_NPIQ_Positive_Change:6mons',
 'DEL_NPIQ_Unknown_Change:6mons',
 'DELSEV_NPIQ_Neg_Change:6mons',
 'DELSEV_NPIQ_No_Change:6mons',
 'DELSEV_NPIQ_Positive_Change:6mons',
 'DELSEV_NPIQ_Unknown_Change:6mons',
 'HALL_NPIQ_Neg_Change:6mons',
 'HALL_NPIQ_No_Change:6mons',
 'HALL_NPIQ_Positive_Change:6mons',
 'HALL_NPIQ_Unknown_Change:6mons',
 'HALLSEV_NPIQ_Neg_Change:6mons',
 'HALLSEV_NPIQ_No_Change:6mons',
 'HALLSEV_NPIQ_Positive_Change:6mons',
 'HALLSEV_NPIQ_Unknown_Change:6mons',
 'AGIT_NPIQ_Neg_Change:6mons',
 'AGIT_NPIQ_No_Change:6mons',
 'AGIT_NPIQ_Positive_Change:6mons',
 'AGIT_NPIQ_Unknown_Change:6mons',
 'AGITSEV_NPIQ_Neg_Change:6mons',
 'AGITSEV_NPIQ_No_Change:6mons',
 'AGITSEV_NPIQ_Positive_Change:6mons',
 'AGITSEV_NPIQ_Unknown_Change:6mons',
 'DEPD_NPIQ_Neg_Change:6mons',
 'DEPD_NPIQ_No_Change:6mons',
 'DEPD_NPIQ_Positive_Change:6mons',
 'DEPD_NPIQ_Unknown_Change:6mons',
 'DEPDSEV_NPIQ_Neg_Change:6mons',
 'DEPDSEV_NPIQ_No_Change:6mons',
 'DEPDSEV_NPIQ_Positive_Change:6mons',
 'DEPDSEV_NPIQ_Unknown_Change:6mons',
 'ANX_NPIQ_Neg_Change:6mons',
 'ANX_NPIQ_No_Change:6mons',
 'ANX_NPIQ_Positive_Change:6mons',
 'ANX_NPIQ_Unknown_Change:6mons',
 'ANXSEV_NPIQ_Neg_Change:6mons',
 'ANXSEV_NPIQ_No_Change:6mons',
 'ANXSEV_NPIQ_Positive_Change:6mons',
 'ANXSEV_NPIQ_Unknown_Change:6mons',
 'ELAT_NPIQ_Neg_Change:6mons',
 'ELAT_NPIQ_No_Change:6mons',
 'ELAT_NPIQ_Positive_Change:6mons',
 'ELAT_NPIQ_Unknown_Change:6mons',
 'ELATSEV_NPIQ_Neg_Change:6mons',
 'ELATSEV_NPIQ_No_Change:6mons',
 'ELATSEV_NPIQ_Positive_Change:6mons',
 'ELATSEV_NPIQ_Unknown_Change:6mons',
 'APA_NPIQ_Neg_Change:6mons',
 'APA_NPIQ_No_Change:6mons',
 'APA_NPIQ_Positive_Change:6mons',
 'APA_NPIQ_Unknown_Change:6mons',
 'APASEV_NPIQ_Neg_Change:6mons',
 'APASEV_NPIQ_No_Change:6mons',
 'APASEV_NPIQ_Positive_Change:6mons',
 'APASEV_NPIQ_Unknown_Change:6mons',
 'DISN_NPIQ_Neg_Change:6mons',
 'DISN_NPIQ_No_Change:6mons',
 'DISN_NPIQ_Positive_Change:6mons',
 'DISN_NPIQ_Unknown_Change:6mons',
 'DISNSEV_NPIQ_Neg_Change:6mons',
 'DISNSEV_NPIQ_No_Change:6mons',
 'DISNSEV_NPIQ_Positive_Change:6mons',
 'DISNSEV_NPIQ_Unknown_Change:6mons',
 'IRR_NPIQ_Neg_Change:6mons',
 'IRR_NPIQ_No_Change:6mons',
 'IRR_NPIQ_Positive_Change:6mons',
 'IRR_NPIQ_Unknown_Change:6mons',
 'IRRSEV_NPIQ_Neg_Change:6mons',
 'IRRSEV_NPIQ_No_Change:6mons',
 'IRRSEV_NPIQ_Positive_Change:6mons',
 'IRRSEV_NPIQ_Unknown_Change:6mons',
 'MOT_NPIQ_Neg_Change:6mons',
 'MOT_NPIQ_No_Change:6mons',
 'MOT_NPIQ_Positive_Change:6mons',
 'MOT_NPIQ_Unknown_Change:6mons',
 'MOTSEV_NPIQ_Neg_Change:6mons',
 'MOTSEV_NPIQ_No_Change:6mons',
 'MOTSEV_NPIQ_Positive_Change:6mons',
 'MOTSEV_NPIQ_Unknown_Change:6mons',
 'NITE_NPIQ_Neg_Change:6mons',
 'NITE_NPIQ_No_Change:6mons',
 'NITE_NPIQ_Positive_Change:6mons',
 'NITE_NPIQ_Unknown_Change:6mons',
 'NITESEV_NPIQ_Neg_Change:6mons',
 'NITESEV_NPIQ_No_Change:6mons',
 'NITESEV_NPIQ_Positive_Change:6mons',
 'NITESEV_NPIQ_Unknown_Change:6mons',
 'APP_NPIQ_Neg_Change:6mons',
 'APP_NPIQ_No_Change:6mons',
 'APP_NPIQ_Positive_Change:6mons',
 'APP_NPIQ_Unknown_Change:6mons',
 'APPSEV_NPIQ_Neg_Change:6mons',
 'APPSEV_NPIQ_No_Change:6mons',
 'APPSEV_NPIQ_Positive_Change:6mons',
 'APPSEV_NPIQ_Unknown_Change:6mons',
 'Pt_Sex:Male',
 'Pt_Sex:Female',
 'Pt_Ethnicity:Non_Hispanic',
 'Pt_Ethnicity:Hispanic',
 'Pt_Ethnicity:Hispanic_Unknown',
 'Pt_Race:White',
 'Pt_Race:African_American',
 'Pt_Race:American_Indian_Alaskan_Native',
 'Pt_Race:Hawaiian_or_Pacific_Islander',
 'Pt_Race:Asian',
 'Pt_Race:Other',
 'Pt_Race:Unknown',
 'Caregiver_Sex:Unknown',
 'Caregiver_Sex:Male',
 'Caregiver_Sex:Female',
 'Caregiver_Ethnicity:Hispanic_Not_Available',
 'Caregiver_Ethnicity:Non_Hispanic',
 'Caregiver_Ethnicity:Hispanic',
 'Caregiver_Ethnicity:Hispanic_Unknown',
 'Caregiver_Race:Not_Available',
 'Caregiver_Race:White',
 'Caregiver_Race:African_American',
 'Caregiver_Race:American_Indian_Alaskan_Native',
 'Caregiver_Race:Hawaiian_or_Pacific_Islander',
 'Caregiver_Race:Asian',
 'Caregiver_Race:Other',
 'Caregiver_Race:Unknown',
 'Caregiver_Pt_Rel:Not_Available',
 'Caregiver_Pt_Rel:Spouse_or_Partner',
 'Caregiver_Pt_Rel:Child',
 'Caregiver_Pt_Rel:Sibling',
 'Caregiver_Pt_Rel:Other_Relative',
 'Caregiver_Pt_Rel:Friend',
 'Caregiver_Pt_Rel:Caregiver',
 'Caregiver_Pt_Rel:Other']

question_dict = {'Pt_Age:latest': 'What is the latest age of the patient?',
 'Caregiver_Age:latest': 'What is the latest age of the caregiver?',
 'MEMORY_CDR_No_Impairment:latest': 'Does the patient have no memory impairment lately?',
 'MEMORY_CDR_Questionable_Impairment:latest': 'Does the patient have questionable memory impairment lately?',
 'MEMORY_CDR_Mild_Impairment:latest': 'Does the patient have mild memory impairment lately?',
 'MEMORY_CDR_Moderate_Impairment:latest': 'Does the patient have moderate memory impairment lately?',
 'MEMORY_CDR_Severe_Impairment:latest': 'Does the patient have severe memory impairment lately?',
 'MEMORY_CDR_Unknown:latest': 'Is the memory impairment of the patient unknown lately?',
 'ORIENT_CDR_No_Impairment:latest': 'Does the patient have no orientation impairment lately?',
 'ORIENT_CDR_Questionable_Impairment:latest': 'Does the patient have questionable orientation impairment lately?',
 'ORIENT_CDR_Mild_Impairment:latest': 'Does the patient have mild orientation impairment lately?',
 'ORIENT_CDR_Moderate_Impairment:latest': 'Does the patient have moderate orientation impairment lately?',
 'ORIENT_CDR_Severe_Impairment:latest': 'Does the patient have severe orientation impairment lately?',
 'ORIENT_CDR_Unknown:latest': 'Is the orientation impairment of the patient unknown lately?',
 'JUDGMENT_CDR_No_Impairment:latest': 'Does the patient have no judgment impairment lately?',
 'JUDGMENT_CDR_Questionable_Impairment:latest': 'Does the patient have questionable judgment impairment lately?',
 'JUDGMENT_CDR_Mild_Impairment:latest': 'Does the patient have mild judgment impairment lately?',
 'JUDGMENT_CDR_Moderate_Impairment:latest': 'Does the patient have moderate judgment impairment lately?',
 'JUDGMENT_CDR_Severe_Impairment:latest': 'Does the patient have severe judgment impairment lately?',
 'JUDGMENT_CDR_Unknown:latest': 'Is the judgment impairment of the patient unknown lately?',
 'COMMUN_CDR_No_Impairment:latest': 'Does the patient have no communication impairment lately?',
 'COMMUN_CDR_Questionable_Impairment:latest': 'Does the patient have questionable communication impairment lately?',
 'COMMUN_CDR_Mild_Impairment:latest': 'Does the patient have mild communication impairment lately?',
 'COMMUN_CDR_Moderate_Impairment:latest': 'Does the patient have moderate communication impairment lately?',
 'COMMUN_CDR_Severe_Impairment:latest': 'Does the patient have severe communication impairment lately?',
 'COMMUN_CDR_Unknown:latest': 'Is the communication impairment of the patient unknown lately?',
 'HOMEHOBB_CDR_No_Impairment:latest': 'Does the patient have no home and hobbies impairment lately?',
 'HOMEHOBB_CDR_Questionable_Impairment:latest': 'Does the patient have questionable home and hobbies impairment lately?',
 'HOMEHOBB_CDR_Mild_Impairment:latest': 'Does the patient have mild home and hobbies impairment lately?',
 'HOMEHOBB_CDR_Moderate_Impairment:latest': 'Does the patient have moderate home and hobbies impairment lately?',
 'HOMEHOBB_CDR_Severe_Impairment:latest': 'Does the patient have severe home and hobbies impairment lately?',
 'HOMEHOBB_CDR_Unknown:latest': 'Is the home and hobbies impairment of the patient unknown lately?',
 'PERSCARE_CDR_No_Impairment:latest': 'Does the patient have no personal care impairment lately?',
 'PERSCARE_CDR_Questionable_Impairment:latest': 'Does the patient have questionable personal care impairment lately?',
 'PERSCARE_CDR_Mild_Impairment:latest': 'Does the patient have mild personal care impairment lately?',
 'PERSCARE_CDR_Moderate_Impairment:latest': 'Does the patient have moderate personal care impairment lately?',
 'PERSCARE_CDR_Severe_Impairment:latest': 'Does the patient have severe personal care impairment lately?',
 'PERSCARE_CDR_Unknown:latest': 'Is the personal care impairment of the patient unknown lately?',
 'COMPORT_CDR_No_Impairment:latest': 'Does the patient have no comportment impairment lately?',
 'COMPORT_CDR_Questionable_Impairment:latest': 'Does the patient have questionable comportment impairment lately?',
 'COMPORT_CDR_Mild_Impairment:latest': 'Does the patient have mild comportment impairment lately?',
 'COMPORT_CDR_Moderate_Impairment:latest': 'Does the patient have moderate comportment impairment lately?',
 'COMPORT_CDR_Severe_Impairment:latest': 'Does the patient have severe comportment impairment lately?',
 'COMPORT_CDR_Unknown:latest': 'Is the comportment impairment of the patient unknown lately?',
 'CDRLANG_CDR_No_Impairment:latest': 'Does the patient have no language impairment lately?',
 'CDRLANG_CDR_Questionable_Impairment:latest': 'Does the patient have questionable language impairment lately?',
 'CDRLANG_CDR_Mild_Impairment:latest': 'Does the patient have mild language impairment lately?',
 'CDRLANG_CDR_Moderate_Impairment:latest': 'Does the patient have moderate language impairment lately?',
 'CDRLANG_CDR_Severe_Impairment:latest': 'Does the patient have severe language impairment lately?',
 'CDRLANG_CDR_Unknown:latest': 'Is the language impairment of the patient unknown lately?',
 'DEL_NPIQ_No_Impairment:latest': 'Does the patient have no delusions lately?',
 'DEL_NPIQ_With_Impairment:latest': 'Does the patient have delusions lately?',
 'DEL_NPIQ_Unknown:latest': 'Is the delusion status of the patient unknown lately?',
 'DELSEV_NPIQ_Mild:latest': 'Does the patient have mild delusions lately?',
 'DELSEV_NPIQ_Moderate:latest': 'Does the patient have moderate delusions lately?',
 'DELSEV_NPIQ_Severe:latest': 'Does the patient have severe delusions lately?',
 'DELSEV_NPIQ_Unknown:latest': 'Is the delusion severity of the patient unknown lately?',
 'HALL_NPIQ_No_Impairment:latest': 'Does the patient have no hallucinations lately?',
 'HALL_NPIQ_With_Impairment:latest': 'Does the patient have hallucinations lately?',
 'HALL_NPIQ_Unknown:latest': 'Is the hallucination status of the patient unknown lately?',
 'HALLSEV_NPIQ_Mild:latest': 'Does the patient have mild hallucinations lately?',
 'HALLSEV_NPIQ_Moderate:latest': 'Does the patient have moderate hallucinations lately?',
 'HALLSEV_NPIQ_Severe:latest': 'Does the patient have severe hallucinations lately?',
 'HALLSEV_NPIQ_Unknown:latest': 'Is the hallucination severity of the patient unknown lately?',
 'AGIT_NPIQ_No_Impairment:latest': 'Does the patient have no agitation lately?',
 'AGIT_NPIQ_With_Impairment:latest': 'Does the patient have agitation lately?',
 'AGIT_NPIQ_Unknown:latest': 'Is the agitation status of the patient unknown lately?',
 'AGITSEV_NPIQ_Mild:latest': 'Does the patient have mild agitation lately?',
 'AGITSEV_NPIQ_Moderate:latest': 'Does the patient have moderate agitation lately?',
 'AGITSEV_NPIQ_Severe:latest': 'Does the patient have severe agitation lately?',
 'AGITSEV_NPIQ_Unknown:latest': 'Is the agitation severity of the patient unknown lately?',
 'DEPD_NPIQ_No_Impairment:latest': 'Does the patient have no depression lately?',
 'DEPD_NPIQ_With_Impairment:latest': 'Does the patient have depression lately?',
 'DEPD_NPIQ_Unknown:latest': 'Is the depression status of the patient unknown lately?',
 'DEPDSEV_NPIQ_Mild:latest': 'Does the patient have mild depression lately?',
 'DEPDSEV_NPIQ_Moderate:latest': 'Does the patient have moderate depression lately?',
 'DEPDSEV_NPIQ_Severe:latest': 'Does the patient have severe depression lately?',
 'DEPDSEV_NPIQ_Unknown:latest': 'Is the depression severity of the patient unknown lately?',
 'ANX_NPIQ_No_Impairment:latest': 'Does the patient have no anxiety lately?',
 'ANX_NPIQ_With_Impairment:latest': 'Does the patient have anxiety lately?',
 'ANX_NPIQ_Unknown:latest': 'Is the anxiety status of the patient unknown lately?',
 'ANXSEV_NPIQ_Mild:latest': 'Does the patient have mild anxiety lately?',
 'ANXSEV_NPIQ_Moderate:latest': 'Does the patient have moderate anxiety lately?',
 'ANXSEV_NPIQ_Severe:latest': 'Does the patient have severe anxiety lately?',
 'ANXSEV_NPIQ_Unknown:latest': 'Is the anxiety severity of the patient unknown lately?',
 'ELAT_NPIQ_No_Impairment:latest': 'Does the patient have no elation lately?',
 'ELAT_NPIQ_With_Impairment:latest': 'Does the patient have elation lately?',
 'ELAT_NPIQ_Unknown:latest': 'Is the elation status of the patient unknown lately?',
 'ELATSEV_NPIQ_Mild:latest': 'Does the patient have mild elation lately?',
 'ELATSEV_NPIQ_Moderate:latest': 'Does the patient have moderate elation lately?',
 'ELATSEV_NPIQ_Severe:latest': 'Does the patient have severe elation lately?',
 'ELATSEV_NPIQ_Unknown:latest': 'Is the elation severity of the patient unknown lately?',
 'APA_NPIQ_No_Impairment:latest': 'Does the patient have no apathy lately?',
 'APA_NPIQ_With_Impairment:latest': 'Does the patient have apathy lately?',
 'APA_NPIQ_Unknown:latest': 'Is the apathy status of the patient unknown lately?',
 'APASEV_NPIQ_Mild:latest': 'Does the patient have mild apathy lately?',
 'APASEV_NPIQ_Moderate:latest': 'Does the patient have moderate apathy lately?',
 'APASEV_NPIQ_Severe:latest': 'Does the patient have severe apathy lately?',
 'APASEV_NPIQ_Unknown:latest': 'Is the apathy severity of the patient unknown lately?',
 'DISN_NPIQ_No_Impairment:latest': 'Does the patient have no disinhibition lately?',
 'DISN_NPIQ_With_Impairment:latest': 'Does the patient have disinhibition lately?',
 'DISN_NPIQ_Unknown:latest': 'Is the disinhibition status of the patient unknown lately?',
 'DISNSEV_NPIQ_Mild:latest': 'Does the patient have mild disinhibition lately?',
 'DISNSEV_NPIQ_Moderate:latest': 'Does the patient have moderate disinhibition lately?',
 'DISNSEV_NPIQ_Severe:latest': 'Does the patient have severe disinhibition lately?',
 'DISNSEV_NPIQ_Unknown:latest': 'Is the disinhibition severity of the patient unknown lately?',
 'IRR_NPIQ_No_Impairment:latest': 'Does the patient have no irritability lately?',
 'IRR_NPIQ_With_Impairment:latest': 'Does the patient have irritability lately?',
 'IRR_NPIQ_Unknown:latest': 'Is the irritability status of the patient unknown lately?',
 'IRRSEV_NPIQ_Mild:latest': 'Does the patient have mild irritability lately?',
 'IRRSEV_NPIQ_Moderate:latest': 'Does the patient have moderate irritability lately?',
 'IRRSEV_NPIQ_Severe:latest': 'Does the patient have severe irritability lately?',
 'IRRSEV_NPIQ_Unknown:latest': 'Is the irritability severity of the patient unknown lately?',
 'MOT_NPIQ_No_Impairment:latest': 'Does the patient have no motor disturbances lately?',
 'MOT_NPIQ_With_Impairment:latest': 'Does the patient have motor disturbances lately?',
 'MOT_NPIQ_Unknown:latest': 'Is the motor disturbance status of the patient unknown lately?',
 'MOTSEV_NPIQ_Mild:latest': 'Does the patient have mild motor disturbances lately?',
 'MOTSEV_NPIQ_Moderate:latest': 'Does the patient have moderate motor disturbances lately?',
 'MOTSEV_NPIQ_Severe:latest': 'Does the patient have severe motor disturbances lately?',
 'MOTSEV_NPIQ_Unknown:latest': 'Is the motor disturbance severity of the patient unknown lately?',
 'NITE_NPIQ_No_Impairment:latest': 'Does the patient have no nighttime behavior disturbances lately?',
 'NITE_NPIQ_With_Impairment:latest': 'Does the patient have nighttime behavior disturbances lately?',
 'NITE_NPIQ_Unknown:latest': 'Is the nighttime behavior disturbance status of the patient unknown lately?',
 'NITESEV_NPIQ_Mild:latest': 'Does the patient have mild nighttime behavior disturbances lately?',
 'NITESEV_NPIQ_Moderate:latest': 'Does the patient have moderate nighttime behavior disturbances lately?',
 'NITESEV_NPIQ_Severe:latest': 'Does the patient have severe nighttime behavior disturbances lately?',
 'NITESEV_NPIQ_Unknown:latest': 'Is the nighttime behavior disturbance severity of the patient unknown lately?',
 'APP_NPIQ_No_Impairment:latest': 'Does the patient have no appetite changes lately?',
 'APP_NPIQ_With_Impairment:latest': 'Does the patient have appetite changes lately?',
 'APP_NPIQ_Unknown:latest': 'Is the appetite change status of the patient unknown lately?',
 'APPSEV_NPIQ_Mild:latest': 'Does the patient have mild appetite changes lately?',
 'APPSEV_NPIQ_Moderate:latest': 'Does the patient have moderate appetite changes lately?',
 'APPSEV_NPIQ_Severe:latest': 'Does the patient have severe appetite changes lately?',
 'APPSEV_NPIQ_Unknown:latest': 'Is the appetite change severity of the patient unknown lately?',
 'MEMORY_CDR_Neg_Change:6mons': "Has the patient's memory shown a negative change in the last 6 months?",
 'MEMORY_CDR_No_Change:6mons': "Has the patient's memory shown no change in the last 6 months?",
 'MEMORY_CDR_Positive_Change:6mons': "Has the patient's memory shown a positive change in the last 6 months?",
 'MEMORY_CDR_Unknown_Change:6mons': "Is the change in the patient's memory unknown in the last 6 months?",
 'ORIENT_CDR_Neg_Change:6mons': "Has the patient's orientation shown a negative change in the last 6 months?",
 'ORIENT_CDR_No_Change:6mons': "Has the patient's orientation shown no change in the last 6 months?",
 'ORIENT_CDR_Positive_Change:6mons': "Has the patient's orientation shown a positive change in the last 6 months?",
 'ORIENT_CDR_Unknown_Change:6mons': "Is the change in the patient's orientation unknown in the last 6 months?",
 'JUDGMENT_CDR_Neg_Change:6mons': "Has the patient's judgment shown a negative change in the last 6 months?",
 'JUDGMENT_CDR_No_Change:6mons': "Has the patient's judgment shown no change in the last 6 months?",
 'JUDGMENT_CDR_Positive_Change:6mons': "Has the patient's judgment shown a positive change in the last 6 months?",
 'JUDGMENT_CDR_Unknown_Change:6mons': "Is the change in the patient's judgment unknown in the last 6 months?",
 'COMMUN_CDR_Neg_Change:6mons': "Has the patient's communication shown a negative change in the last 6 months?",
 'COMMUN_CDR_No_Change:6mons': "Has the patient's communication shown no change in the last 6 months?",
 'COMMUN_CDR_Positive_Change:6mons': "Has the patient's communication shown a positive change in the last 6 months?",
 'COMMUN_CDR_Unknown_Change:6mons': "Is the change in the patient's communication unknown in the last 6 months?",
 'HOMEHOBB_CDR_Neg_Change:6mons': "Has the patient's home and hobbies shown a negative change in the last 6 months?",
 'HOMEHOBB_CDR_No_Change:6mons': "Has the patient's home and hobbies shown no change in the last 6 months?",
 'HOMEHOBB_CDR_Positive_Change:6mons': "Has the patient's home and hobbies shown a positive change in the last 6 months?",
 'HOMEHOBB_CDR_Unknown_Change:6mons': "Is the change in the patient's home and hobbies unknown in the last 6 months?",
 'PERSCARE_CDR_Neg_Change:6mons': "Has the patient's personal care shown a negative change in the last 6 months?",
 'PERSCARE_CDR_No_Change:6mons': "Has the patient's personal care shown no change in the last 6 months?",
 'PERSCARE_CDR_Positive_Change:6mons': "Has the patient's personal care shown a positive change in the last 6 months?",
 'PERSCARE_CDR_Unknown_Change:6mons': "Is the change in the patient's personal care unknown in the last 6 months?",
 'COMPORT_CDR_Neg_Change:6mons': "Has the patient's comportment shown a negative change in the last 6 months?",
 'COMPORT_CDR_No_Change:6mons': "Has the patient's comportment shown no change in the last 6 months?",
 'COMPORT_CDR_Positive_Change:6mons': "Has the patient's comportment shown a positive change in the last 6 months?",
 'COMPORT_CDR_Unknown_Change:6mons': "Is the change in the patient's comportment unknown in the last 6 months?",
 'CDRLANG_CDR_Neg_Change:6mons': "Has the patient's language shown a negative change in the last 6 months?",
 'CDRLANG_CDR_No_Change:6mons': "Has the patient's language shown no change in the last 6 months?",
 'CDRLANG_CDR_Positive_Change:6mons': "Has the patient's language shown a positive change in the last 6 months?",
 'CDRLANG_CDR_Unknown_Change:6mons': "Is the change in the patient's language unknown in the last 6 months?",
 'DEL_NPIQ_Neg_Change:6mons': "Have the patient's delusions shown a negative change in the last 6 months?",
 'DEL_NPIQ_No_Change:6mons': "Have the patient's delusions shown no change in the last 6 months?",
 'DEL_NPIQ_Positive_Change:6mons': "Have the patient's delusions shown a positive change in the last 6 months?",
 'DEL_NPIQ_Unknown_Change:6mons': "Is the change in the patient's delusions unknown in the last 6 months?",
 'DELSEV_NPIQ_Neg_Change:6mons': "Have the patient's delusions severity shown a negative change in the last 6 months?",
 'DELSEV_NPIQ_No_Change:6mons': "Have the patient's delusions severity shown no change in the last 6 months?",
 'DELSEV_NPIQ_Positive_Change:6mons': "Have the patient's delusions severity shown a positive change in the last 6 months?",
 'DELSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's delusions severity unknown in the last 6 months?",
 'HALL_NPIQ_Neg_Change:6mons': "Have the patient's hallucinations shown a negative change in the last 6 months?",
 'HALL_NPIQ_No_Change:6mons': "Have the patient's hallucinations shown no change in the last 6 months?",
 'HALL_NPIQ_Positive_Change:6mons': "Have the patient's hallucinations shown a positive change in the last 6 months?",
 'HALL_NPIQ_Unknown_Change:6mons': "Is the change in the patient's hallucinations unknown in the last 6 months?",
 'HALLSEV_NPIQ_Neg_Change:6mons': "Have the patient's hallucinations severity shown a negative change in the last 6 months?",
 'HALLSEV_NPIQ_No_Change:6mons': "Have the patient's hallucinations severity shown no change in the last 6 months?",
 'HALLSEV_NPIQ_Positive_Change:6mons': "Have the patient's hallucinations severity shown a positive change in the last 6 months?",
 'HALLSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's hallucinations severity unknown in the last 6 months?",
 'AGIT_NPIQ_Neg_Change:6mons': "Has the patient's agitation shown a negative change in the last 6 months?",
 'AGIT_NPIQ_No_Change:6mons': "Has the patient's agitation shown no change in the last 6 months?",
 'AGIT_NPIQ_Positive_Change:6mons': "Has the patient's agitation shown a positive change in the last 6 months?",
 'AGIT_NPIQ_Unknown_Change:6mons': "Is the change in the patient's agitation unknown in the last 6 months?",
 'AGITSEV_NPIQ_Neg_Change:6mons': "Has the patient's agitation severity shown a negative change in the last 6 months?",
 'AGITSEV_NPIQ_No_Change:6mons': "Has the patient's agitation severity shown no change in the last 6 months?",
 'AGITSEV_NPIQ_Positive_Change:6mons': "Has the patient's agitation severity shown a positive change in the last 6 months?",
 'AGITSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's agitation severity unknown in the last 6 months?",
 'DEPD_NPIQ_Neg_Change:6mons': "Has the patient's depression shown a negative change in the last 6 months?",
 'DEPD_NPIQ_No_Change:6mons': "Has the patient's depression shown no change in the last 6 months?",
 'DEPD_NPIQ_Positive_Change:6mons': "Has the patient's depression shown a positive change in the last 6 months?",
 'DEPD_NPIQ_Unknown_Change:6mons': "Is the change in the patient's depression unknown in the last 6 months?",
 'DEPDSEV_NPIQ_Neg_Change:6mons': "Has the patient's depression severity shown a negative change in the last 6 months?",
 'DEPDSEV_NPIQ_No_Change:6mons': "Has the patient's depression severity shown no change in the last 6 months?",
 'DEPDSEV_NPIQ_Positive_Change:6mons': "Has the patient's depression severity shown a positive change in the last 6 months?",
 'DEPDSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's depression severity unknown in the last 6 months?",
 'ANX_NPIQ_Neg_Change:6mons': "Has the patient's anxiety shown a negative change in the last 6 months?",
 'ANX_NPIQ_No_Change:6mons': "Has the patient's anxiety shown no change in the last 6 months?",
 'ANX_NPIQ_Positive_Change:6mons': "Has the patient's anxiety shown a positive change in the last 6 months?",
 'ANX_NPIQ_Unknown_Change:6mons': "Is the change in the patient's anxiety unknown in the last 6 months?",
 'ANXSEV_NPIQ_Neg_Change:6mons': "Has the patient's anxiety severity shown a negative change in the last 6 months?",
 'ANXSEV_NPIQ_No_Change:6mons': "Has the patient's anxiety severity shown no change in the last 6 months?",
 'ANXSEV_NPIQ_Positive_Change:6mons': "Has the patient's anxiety severity shown a positive change in the last 6 months?",
 'ANXSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's anxiety severity unknown in the last 6 months?",
 'ELAT_NPIQ_Neg_Change:6mons': "Has the patient's elation shown a negative change in the last 6 months?",
 'ELAT_NPIQ_No_Change:6mons': "Has the patient's elation shown no change in the last 6 months?",
 'ELAT_NPIQ_Positive_Change:6mons': "Has the patient's elation shown a positive change in the last 6 months?",
 'ELAT_NPIQ_Unknown_Change:6mons': "Is the change in the patient's elation unknown in the last 6 months?",
 'ELATSEV_NPIQ_Neg_Change:6mons': "Has the patient's elation severity shown a negative change in the last 6 months?",
 'ELATSEV_NPIQ_No_Change:6mons': "Has the patient's elation severity shown no change in the last 6 months?",
 'ELATSEV_NPIQ_Positive_Change:6mons': "Has the patient's elation severity shown a positive change in the last 6 months?",
 'ELATSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's elation severity unknown in the last 6 months?",
 'APA_NPIQ_Neg_Change:6mons': "Has the patient's apathy shown a negative change in the last 6 months?",
 'APA_NPIQ_No_Change:6mons': "Has the patient's apathy shown no change in the last 6 months?",
 'APA_NPIQ_Positive_Change:6mons': "Has the patient's apathy shown a positive change in the last 6 months?",
 'APA_NPIQ_Unknown_Change:6mons': "Is the change in the patient's apathy unknown in the last 6 months?",
 'APASEV_NPIQ_Neg_Change:6mons': "Has the patient's apathy severity shown a negative change in the last 6 months?",
 'APASEV_NPIQ_No_Change:6mons': "Has the patient's apathy severity shown no change in the last 6 months?",
 'APASEV_NPIQ_Positive_Change:6mons': "Has the patient's apathy severity shown a positive change in the last 6 months?",
 'APASEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's apathy severity unknown in the last 6 months?",
 'DISN_NPIQ_Neg_Change:6mons': "Has the patient's disinhibition shown a negative change in the last 6 months?",
 'DISN_NPIQ_No_Change:6mons': "Has the patient's disinhibition shown no change in the last 6 months?",
 'DISN_NPIQ_Positive_Change:6mons': "Has the patient's disinhibition shown a positive change in the last 6 months?",
 'DISN_NPIQ_Unknown_Change:6mons': "Is the change in the patient's disinhibition unknown in the last 6 months?",
 'DISNSEV_NPIQ_Neg_Change:6mons': "Has the patient's disinhibition severity shown a negative change in the last 6 months?",
 'DISNSEV_NPIQ_No_Change:6mons': "Has the patient's disinhibition severity shown no change in the last 6 months?",
 'DISNSEV_NPIQ_Positive_Change:6mons': "Has the patient's disinhibition severity shown a positive change in the last 6 months?",
 'DISNSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's disinhibition severity unknown in the last 6 months?",
 'IRR_NPIQ_Neg_Change:6mons': "Has the patient's irritability shown a negative change in the last 6 months?",
 'IRR_NPIQ_No_Change:6mons': "Has the patient's irritability shown no change in the last 6 months?",
 'IRR_NPIQ_Positive_Change:6mons': "Has the patient's irritability shown a positive change in the last 6 months?",
 'IRR_NPIQ_Unknown_Change:6mons': "Is the change in the patient's irritability unknown in the last 6 months?",
 'IRRSEV_NPIQ_Neg_Change:6mons': "Has the patient's irritability severity shown a negative change in the last 6 months?",
 'IRRSEV_NPIQ_No_Change:6mons': "Has the patient's irritability severity shown no change in the last 6 months?",
 'IRRSEV_NPIQ_Positive_Change:6mons': "Has the patient's irritability severity shown a positive change in the last 6 months?",
 'IRRSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's irritability severity unknown in the last 6 months?",
 'MOT_NPIQ_Neg_Change:6mons': "Have the patient's motor disturbances shown a negative change in the last 6 months?",
 'MOT_NPIQ_No_Change:6mons': "Have the patient's motor disturbances shown no change in the last 6 months?",
 'MOT_NPIQ_Positive_Change:6mons': "Have the patient's motor disturbances shown a positive change in the last 6 months?",
 'MOT_NPIQ_Unknown_Change:6mons': "Is the change in the patient's motor disturbances unknown in the last 6 months?",
 'MOTSEV_NPIQ_Neg_Change:6mons': "Have the patient's motor disturbances severity shown a negative change in the last 6 months?",
 'MOTSEV_NPIQ_No_Change:6mons': "Have the patient's motor disturbances severity shown no change in the last 6 months?",
 'MOTSEV_NPIQ_Positive_Change:6mons': "Have the patient's motor disturbances severity shown a positive change in the last 6 months?",
 'MOTSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's motor disturbances severity unknown in the last 6 months?",
 'NITE_NPIQ_Neg_Change:6mons': "Have the patient's nighttime behavior disturbances shown a negative change in the last 6 months?",
 'NITE_NPIQ_No_Change:6mons': "Have the patient's nighttime behavior disturbances shown no change in the last 6 months?",
 'NITE_NPIQ_Positive_Change:6mons': "Have the patient's nighttime behavior disturbances shown a positive change in the last 6 months?",
 'NITE_NPIQ_Unknown_Change:6mons': "Is the change in the patient's nighttime behavior disturbances unknown in the last 6 months?",
 'NITESEV_NPIQ_Neg_Change:6mons': "Have the patient's nighttime behavior disturbances severity shown a negative change in the last 6 months?",
 'NITESEV_NPIQ_No_Change:6mons': "Have the patient's nighttime behavior disturbances severity shown no change in the last 6 months?",
 'NITESEV_NPIQ_Positive_Change:6mons': "Have the patient's nighttime behavior disturbances severity shown a positive change in the last 6 months?",
 'NITESEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's nighttime behavior disturbances severity unknown in the last 6 months?",
 'APP_NPIQ_Neg_Change:6mons': "Have the patient's appetite changes shown a negative change in the last 6 months?",
 'APP_NPIQ_No_Change:6mons': "Have the patient's appetite changes shown no change in the last 6 months?",
 'APP_NPIQ_Positive_Change:6mons': "Have the patient's appetite changes shown a positive change in the last 6 months?",
 'APP_NPIQ_Unknown_Change:6mons': "Is the change in the patient's appetite changes unknown in the last 6 months?",
 'APPSEV_NPIQ_Neg_Change:6mons': "Have the patient's appetite changes severity shown a negative change in the last 6 months?",
 'APPSEV_NPIQ_No_Change:6mons': "Have the patient's appetite changes severity shown no change in the last 6 months?",
 'APPSEV_NPIQ_Positive_Change:6mons': "Have the patient's appetite changes severity shown a positive change in the last 6 months?",
 'APPSEV_NPIQ_Unknown_Change:6mons': "Is the change in the patient's appetite changes severity unknown in the last 6 months?",
 'Pt_Sex:Male': 'Is the patient male?',
 'Pt_Sex:Female': 'Is the patient female?',
 'Pt_Ethnicity:Non_Hispanic': 'Is the patient non-Hispanic?',
 'Pt_Ethnicity:Hispanic': 'Is the patient Hispanic?',
 'Pt_Ethnicity:Hispanic_Unknown': "Is the patient's Hispanic ethnicity unknown?",
 'Pt_Race:White': 'Is the patient white?',
 'Pt_Race:African_American': 'Is the patient African American?',
 'Pt_Race:American_Indian_Alaskan_Native': 'Is the patient American Indian or Alaskan Native?',
 'Pt_Race:Hawaiian_or_Pacific_Islander': 'Is the patient Hawaiian or Pacific Islander?',
 'Pt_Race:Asian': 'Is the patient Asian?',
 'Pt_Race:Other': 'Is the patient of another race?',
 'Pt_Race:Unknown': "Is the patient's race unknown?",
 'Caregiver_Sex:Unknown': "Is the caregiver's sex unknown?",
 'Caregiver_Sex:Male': 'Is the caregiver male?',
 'Caregiver_Sex:Female': 'Is the caregiver female?',
 'Caregiver_Ethnicity:Hispanic_Not_Available': "Is the caregiver's Hispanic ethnicity not available?",
 'Caregiver_Ethnicity:Non_Hispanic': 'Is the caregiver non-Hispanic?',
 'Caregiver_Ethnicity:Hispanic': 'Is the caregiver Hispanic?',
 'Caregiver_Ethnicity:Hispanic_Unknown': "Is the caregiver's Hispanic ethnicity unknown?",
 'Caregiver_Race:Not_Available': "Is the caregiver's race not available?",
 'Caregiver_Race:White': 'Is the caregiver white?',
 'Caregiver_Race:African_American': 'Is the caregiver African American?',
 'Caregiver_Race:American_Indian_Alaskan_Native': 'Is the caregiver American Indian or Alaskan Native?',
 'Caregiver_Race:Hawaiian_or_Pacific_Islander': 'Is the caregiver Hawaiian or Pacific Islander?',
 'Caregiver_Race:Asian': 'Is the caregiver Asian?',
 'Caregiver_Race:Other': 'Is the caregiver of another race?',
 'Caregiver_Race:Unknown': "Is the caregiver's race unknown?",
 'Caregiver_Pt_Rel:Not_Available': "Is the caregiver's relationship to the patient not available?",
 'Caregiver_Pt_Rel:Spouse_or_Partner': "Is the caregiver the patient's spouse or partner?",
 'Caregiver_Pt_Rel:Child': "Is the caregiver the patient's child?",
 'Caregiver_Pt_Rel:Sibling': "Is the caregiver the patient's sibling?",
 'Caregiver_Pt_Rel:Other_Relative': 'Is the caregiver another relative of the patient?',
 'Caregiver_Pt_Rel:Friend': 'Is the caregiver a friend of the patient?',
 'Caregiver_Pt_Rel:Caregiver': 'Is the caregiver a professional caregiver?',
 'Caregiver_Pt_Rel:Other': 'Is the caregiver someone else?'}

npi_class = {'DEL': 'Hallucinations and Delusions',
 'HAL': 'Hallucinations and Delusions',
 'AGIT': 'Agitation',
 'DEPD': 'Depression',
 'ANX': 'Anxiety',
 'ELAT': 'Elation',
 'APA': 'Apathy',
 'DISN': 'Disinhibition',
 'IRR': 'Agitation',
 'MOT': 'Motor Behaviors',
 'NITE': 'Sleep Problem',
 'APP': 'Appetite'}

model_path = "./model/xgboost_model_20241031_133126.pkl"
